services:
  - type: web
    name: finance-ai-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: POSTGRES_DB
        fromDatabase:
          name: finance-ai-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: finance-ai-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: finance-ai-db
          property: password
      - key: POSTGRES_SERVER
        fromDatabase:
          name: finance-ai-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: finance-ai-db
          property: port

databases:
  - name: finance-ai-db
    databaseName: family_finance
    plan: free 